<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Permohonan Bantuan</name>
   <tag></tag>
   <elementGuidId>26b4fb99-00c6-4c6b-a409-ad92a90d42b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-collapsible-nav']/ul/li[18]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>899e7941-80e9-4363-b2b4-169a6aca9c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://smartpbf-p2-dev.digital-healthcare.id/aw_helpdesk2/ticket/</value>
      <webElementGuid>6c933d39-94d0-4336-871c-7ee36198854c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Permohonan Bantuan</value>
      <webElementGuid>d9463716-d0d3-40aa-8f9c-0f5bb794a2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-collapsible-nav&quot;)/ul[@class=&quot;nav items&quot;]/li[@class=&quot;nav item&quot;]/a[1]</value>
      <webElementGuid>cb211f69-7055-4e76-bc32-bb3c155febb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-collapsible-nav']/ul/li[18]/a</value>
      <webElementGuid>70c495b9-4d3d-4659-980d-1b90b0e6bf7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Permohonan Bantuan')]</value>
      <webElementGuid>3d45d59b-ad45-49b4-a2d1-ad7b3ff12751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Akun Pengguna'])[1]/following::a[1]</value>
      <webElementGuid>bb0e2d94-c2d7-47a7-aeb8-e5d21bae8463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profil Perusahaan'])[1]/following::a[2]</value>
      <webElementGuid>f91b7a6f-ec83-4d98-8831-32de1a6b8715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifikasi'])[2]/preceding::a[1]</value>
      <webElementGuid>70f30392-5a84-482c-b62a-ca1ebe908b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotline'])[1]/preceding::a[2]</value>
      <webElementGuid>88cabef6-be4b-4f98-ab98-637fd4625e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Permohonan Bantuan']/parent::*</value>
      <webElementGuid>c0ac101d-b276-426f-a093-e9f6e513eec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://smartpbf-p2-dev.digital-healthcare.id/aw_helpdesk2/ticket/')]</value>
      <webElementGuid>85e4c789-c970-4c06-ba62-f87fbe361b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[18]/a</value>
      <webElementGuid>b251b6a5-0231-4ba7-9588-83134630e649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://smartpbf-p2-dev.digital-healthcare.id/aw_helpdesk2/ticket/' and (text() = 'Permohonan Bantuan' or . = 'Permohonan Bantuan')]</value>
      <webElementGuid>a6a9ca0d-f00c-4a3c-89f8-8687ebd0fc3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
