<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_STAGMB000000637_1</name>
   <tag></tag>
   <elementGuidId>66f5440a-3e71-47ce-b8ce-3c6ebcac4134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-JVQ78BX-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-JVQ78BX-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4a5f5773-667d-44c3-b479-8e9d90cc8e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>27399b98-38dd-43fe-b9d7-30d128259043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-JVQ78BX-container</value>
      <webElementGuid>7d5b985d-428c-4c1e-b211-4bb2a609897c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>f0d00f31-1c38-4160-9b6a-fe4842acb89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e14d7c60-b317-41e5-b1fa-bee4c945df62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>STAGMB000000637</value>
      <webElementGuid>f843aa81-00d7-4b5a-aa93-25bb3658c83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>STAGMB000000637</value>
      <webElementGuid>ecdc5ee5-3b26-48ea-a270-39e50ee8e866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-JVQ78BX-container&quot;)</value>
      <webElementGuid>0c3e5337-ab5a-45e5-99d2-e9f3083740e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-JVQ78BX-container']</value>
      <webElementGuid>a3f845b6-a0cc-45e6-bf5b-ef17aa6fd19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact-form']/fieldset/div[6]/div/div/fieldset/div[4]/div/span/span/span/span</value>
      <webElementGuid>109df4fd-56f8-4300-84c7-b26aee7d37ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesanan'])[1]/following::span[4]</value>
      <webElementGuid>df27e1f5-0156-4321-98c3-5683ec8c1505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Permintaan'])[1]/following::span[5]</value>
      <webElementGuid>1b701fba-d3ae-49cb-bd7a-9b02d039f071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim'])[1]/preceding::span[3]</value>
      <webElementGuid>db0c18b2-2206-40d9-b2de-380178cdd3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info@medbiz.co.id'])[1]/preceding::span[5]</value>
      <webElementGuid>e02f0e18-3fd2-4754-994e-66974c42d154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/span/span/span</value>
      <webElementGuid>44811451-5957-4b17-bac0-6b55b8ae954c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-JVQ78BX-container' and @title = 'STAGMB000000637' and (text() = 'STAGMB000000637' or . = 'STAGMB000000637')]</value>
      <webElementGuid>f0198341-a337-46bb-bf57-70c3e7e422e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
