<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_STAGMB000000637</name>
   <tag></tag>
   <elementGuidId>45c86003-7432-46b3-953e-4317fa9e511a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-VUVAEM9-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-VUVAEM9-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3c176ab1-71b9-4413-8b75-c12f64d5d13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>916c453e-e2a9-4cbc-9716-04c566d53469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-VUVAEM9-container</value>
      <webElementGuid>8e80aebf-245b-4dae-ac35-0672aa1b4783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a8f80425-fbe4-4edb-b3bb-fe10667de1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bcbe3665-8d97-4438-b6da-b97d09d9487c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>STAGMB000000637</value>
      <webElementGuid>ad71b4a4-9e9c-4d49-a176-0347a71302e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>STAGMB000000637</value>
      <webElementGuid>9489b039-7cb5-479f-a83f-d8bfa9ba54c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-VUVAEM9-container&quot;)</value>
      <webElementGuid>b51c6238-b178-40a3-b1ec-075b9290ea31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-VUVAEM9-container']</value>
      <webElementGuid>326b022e-424b-419d-a96f-846d9a00a7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact-form']/fieldset/div[6]/div/div/fieldset/div[4]/div/span/span/span/span</value>
      <webElementGuid>16fb517e-e543-4f26-89a9-54779ce792c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesanan'])[1]/following::span[4]</value>
      <webElementGuid>f0b60efc-9426-4297-8174-a62a61e5d03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Permintaan'])[1]/following::span[5]</value>
      <webElementGuid>38ac2391-0ed6-4ba6-901a-f511e2dfdd31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim'])[1]/preceding::span[3]</value>
      <webElementGuid>93855eea-bfb1-4044-9f6b-06565de366bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info@medbiz.co.id'])[1]/preceding::span[5]</value>
      <webElementGuid>c1131453-6fca-4db3-942a-b23e34082341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/span/span/span</value>
      <webElementGuid>aefcb1fb-6a1d-4284-90b6-5f3d8e685903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-VUVAEM9-container' and @title = 'STAGMB000000637' and (text() = 'STAGMB000000637' or . = 'STAGMB000000637')]</value>
      <webElementGuid>684f7089-657c-4114-a3b7-aa01f0edb1be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
