<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Belum ditetapkan</name>
   <tag></tag>
   <elementGuidId>48451841-eea2-4b33-9a67-60690edd51db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-CWO6PL5-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-CWO6PL5-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>05a38e90-f5f6-4e90-adba-c959661a3e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>928c02e4-17c7-4cc6-bab8-e0daac89a170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-CWO6PL5-container</value>
      <webElementGuid>7da8e65e-d087-4254-97d0-b40cbc8660a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>9ffaa903-0885-4037-9219-344a0e3dc7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>466699ab-cee1-4081-b615-895e6312fe01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Belum ditetapkan</value>
      <webElementGuid>4fb09b4a-18ff-4f55-92e8-0f6645dc5b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belum ditetapkan</value>
      <webElementGuid>8cf91146-7fb8-48f6-a08b-1138a99efbb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-CWO6PL5-container&quot;)</value>
      <webElementGuid>382dbd6f-cee5-4eb9-a073-084b7ac08331</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-CWO6PL5-container']</value>
      <webElementGuid>f04748fb-7bd3-4e8b-b2f1-8115947130c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact-form']/fieldset/div[6]/div/div/fieldset/div[4]/div/span/span/span/span</value>
      <webElementGuid>90430160-cf0a-47dc-88d2-17044d81bd93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesanan'])[1]/following::span[4]</value>
      <webElementGuid>817b0e3a-808e-4ba5-a7b2-2159733cdf93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Permintaan'])[1]/following::span[5]</value>
      <webElementGuid>2983f103-a527-409e-9881-b7f9a25439cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim'])[1]/preceding::span[3]</value>
      <webElementGuid>2338b000-a207-4373-846a-819de406ab5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info@medbiz.co.id'])[1]/preceding::span[5]</value>
      <webElementGuid>66f44372-c157-45a3-9ccc-c9ac7fa3cc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/span/span/span</value>
      <webElementGuid>238aedca-b281-4b7d-aa9f-a2c5ebbced8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-CWO6PL5-container' and @title = 'Belum ditetapkan' and (text() = 'Belum ditetapkan' or . = 'Belum ditetapkan')]</value>
      <webElementGuid>fd57bcb6-ada0-4bed-9ec5-95fb8d22bcfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
