<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Belum ditetapkan_1</name>
   <tag></tag>
   <elementGuidId>2fda3ce7-a7d1-4ba2-834a-b08c98731c51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-IH9C75D-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-IH9C75D-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5640924b-88c5-443e-8829-fcdcf906b5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>70671e22-7874-45b0-b577-a24de49cc954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-IH9C75D-container</value>
      <webElementGuid>e9422658-d128-41be-b302-17c665f0deab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>347bd5f7-c65e-45a6-96ed-24ece2166493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f472e140-8af0-4ef9-af84-cfde58e92cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Belum ditetapkan</value>
      <webElementGuid>d3df072b-ba22-47be-9ad6-fda2f5dbe946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belum ditetapkan</value>
      <webElementGuid>dc0a9571-35f5-4bb1-8c63-ae8aa2b6db08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-IH9C75D-container&quot;)</value>
      <webElementGuid>cc685362-c3ae-4b6b-b39c-d381e3501c02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-IH9C75D-container']</value>
      <webElementGuid>c0fb4421-0e6e-4312-9512-3f4ff344ec9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact-form']/fieldset/div[6]/div/div/fieldset/div[4]/div/span/span/span/span</value>
      <webElementGuid>bae6a9e1-47bc-4b57-9763-38dcb9dd88e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesanan'])[1]/following::span[4]</value>
      <webElementGuid>a09fc07e-8588-4db1-9ee4-5e2faa9130ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Permintaan'])[1]/following::span[5]</value>
      <webElementGuid>9961d847-21cc-42ea-85dd-318c991d7339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim'])[1]/preceding::span[3]</value>
      <webElementGuid>574592d1-52f8-4635-9819-4991f75d24b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info@medbiz.co.id'])[1]/preceding::span[5]</value>
      <webElementGuid>ba0ba650-9e1d-4831-ba1a-0614b47e8bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/span/span/span</value>
      <webElementGuid>2e6c88c0-9041-48a6-96f9-810368f76491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-IH9C75D-container' and @title = 'Belum ditetapkan' and (text() = 'Belum ditetapkan' or . = 'Belum ditetapkan')]</value>
      <webElementGuid>e8504bd5-4cc3-427e-affd-6c50089c9a2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
