<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pemesanan Saya</name>
   <tag></tag>
   <elementGuidId>d470cfd7-98e2-4ca9-8d5a-5e096fd3fc4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-collapsible-nav']/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b86beec5-1d80-4f21-a418-3cf818f98f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://smartpbf-p2-dev.digital-healthcare.id/sales/order/history/</value>
      <webElementGuid>419daa28-43d9-44cb-8c79-e6623a3a9dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pemesanan Saya</value>
      <webElementGuid>850dc245-128b-46b3-84ce-68d668871a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-collapsible-nav&quot;)/ul[@class=&quot;nav items&quot;]/li[@class=&quot;nav item&quot;]/a[1]</value>
      <webElementGuid>25c80f71-55fa-42b0-917c-46b4dde5d739</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-collapsible-nav']/ul/li[3]/a</value>
      <webElementGuid>01da5546-58fc-4f59-9f5f-3ed2a461cc7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Pemesanan Saya')])[3]</value>
      <webElementGuid>fc18c2ca-3483-4499-874c-24a1cb9d6212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penawaran Saya'])[3]/following::a[1]</value>
      <webElementGuid>cef8af4d-8ab5-4d83-9aa0-9b9fec74853b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akun Saya'])[6]/following::a[2]</value>
      <webElementGuid>7ffe0ec0-0e18-447b-b072-f5c4d2e65e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Yang Belum Dibayar'])[1]/preceding::a[1]</value>
      <webElementGuid>d2f3c70c-3aa0-40c1-a4ce-afcd2069db3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Yang Melewati Tanggal Jatuh Tempo'])[1]/preceding::a[2]</value>
      <webElementGuid>4c89c1db-eebd-4a3c-91a2-4b571cf66c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://smartpbf-p2-dev.digital-healthcare.id/sales/order/history/')])[4]</value>
      <webElementGuid>5f6bf7a6-c35e-4777-b25e-2cb41bef839f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/a</value>
      <webElementGuid>a1f51707-3391-4230-adea-8b8489957ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://smartpbf-p2-dev.digital-healthcare.id/sales/order/history/' and (text() = 'Pemesanan Saya' or . = 'Pemesanan Saya')]</value>
      <webElementGuid>14ec24de-aeb8-4d18-8024-8db0125fae75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
